### ISSUE TITLE
i don't think this works

### ISSUE THREAD

**Issue by micampbell** [sidneycadot/quartic#1]
I'm not sure, but when I converted the code to a different language - i did not pass the tests. If it didn't work for you, I suggest you remove it so that others don't waste time forking your repo.

**Comment by sidneycadot** [comment]
Can you be more specific? Post your code. I am willing to wager a considerable sum that my code is correct.

Just saying "I reimplemented your code, it doesn't work, perhaps you should remove your repo" is pretty weird.

Unless you come up with something more concrete, I will close this issue soon.

**Comment by micampbell** [comment]
you're right. that was not a polite way to put it. I'll look into it more before I repost a comment. But, just so I know - does your code pass your test?

**Comment by sidneycadot** [comment]
Yes, it does.

**Comment by sidneycadot** [comment]
For reference, here's the output of the test program run on my system:

```
Running 1000000 test cases. Only errors larger than 1e-08 are shown:
    Testcase 186329 has total error 3.12354e-08
    Testcase 302697 has total error 1.5591e-08
    Testcase 515704 has total error 9.26518e-08
    Testcase 527862 has total error 2.17872e-08
    Testcase 629300 has total error 2.18238e-08
    Testcase 652189 has total error 9.13776e-07
    Testcase 722419 has total error 2.6402e-08
    Testcase 748938 has total error 2.10046e-08
    Testcase 928726 has total error 1.49857e-08
    Testcase 999677 has total error 3.14548e-08
done.
```

The test program constructs 1 million test cases with complex roots; starting from randomly selected roots in the [-10..+10] + i*[-10..+10] range, it constructs a quartic polynomial from them, then solves the polynomial roots from the polynomial coefficients, and calculates the distance of the set of roots found to the original randomly selected roots, which will ideally be zero but will be a small positive value due to numerical errors.

Out of the 1 million test cases, the cases above are the 'worst' ones, showing errors in the order of 1e-7 .. 1e-8, which is pretty much in line with the order-of-magnitude numerical error you'd expect to see.

If you reproduce the solver and test programs, you should see similar (small) errors.

**Comment by micampbell** [comment]
This is excellent! Your code is very short compared to other strategies. Straightforward to use in other many applications.
